### ISSUE TITLE
Syntax error prevents admin from logging in to Wordpress

### ISSUE THREAD

**Issue by Lat91** [projectestac/wordpress-theme-astra#1]
When an admin is attempting to login to wordpress via /wp-admin the following error is generated and prevents login:

AH01071: Got error 'PHP message: PHP Parse error:  syntax error, unexpected ')' in /opt/bitnami/apps/wordpress/htdocs/wp-content/themes/astra/inc/core/class-astra-admin-settings.php on line 248\n'

line 247 has an errant comma at the end of it that seems to cause this.

$ai_image_path,

**Comment by toniginard** [comment]
Hi, @Lat91,

We are not the developers of the Astra theme and we don't provide any kind of support involving it. This repository is just a place we have to host a copy of the code for our convenience. To ask for support, I suggest to contact the Brainstormforce team or anyone able to provide that support.


Best wishes,
